global:
  namespace: todo-list-prod
  tlsSecretName: niyov-wildcard-certificate-tls
  registryCredentialsSecretName: registry-credentials
  
api:
  ingress:
    name: todo-list-api
    host: api-todo-list.niyov.com

  service:
    name: todo-list-api
    port: 80
    targetPort: 3001

  deployment:
    name: todo-list-api
    replicas: 1
    apiContainer:
      name: todo-list-api
      image: harbor.niyov.com/applications/todo-list-api:2.0.1
      containerPort: 3001
    secretsName: todolist-api-secrets

client:
  ingress:
    name: todo-list-client
    host: todo-list.niyov.com
  
  service:
    name: todo-list-client
    port: 80
    targetPort: 80

  deployment:
    name: todo-list-client
    replicas: 1
    clientContainer:
      name: todo-list-client
      image: harbor.niyov.com/applications/todo-list-client:2.0.1
      containerPort: 80

db:
  service:
    name: todo-list-db
    port: 27017
    targetPort: 27017

  deployment:
    name: todo-list-db
    replicas: 1
    dbContainer:
      name: todo-list-mongo
      image: mongo:7.0.0
      containerPort: 27017
    volumes:
      pv:
        name: todo-list-db-pv
        hostPath: /nfs/volumes/todo-list-mongo-db
      pvc:
        name: todo-list-db-pvc
      dbStorage:
        name: db-storage
        mountPath: /data/db
