apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.deployment.volumes.pv.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.deployment.volumes.pv.hostPath }}