apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.deployment.volumes.pvc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi