apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.client.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.client.deployment.clientContainer.name }}
        image: {{ .Values.client.deployment.clientContainer.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.client.deployment.clientContainer.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.client.deployment.clientContainer.requests.cpu }}
          limits:
            cpu: {{ .Values.client.deployment.clientContainer.limits.cpu }}
      imagePullSecrets:
      - name: {{ .Values.global.registryCredentialsSecretName }}