
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.service.name }}
spec:
  selector:
    app: {{ .Values.client.deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
  type: ClusterIP
