apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deployment.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.api.deployment.apiContainer.name }}
        image: {{ .Values.api.deployment.apiContainer.image }}
        ports: 
        - containerPort: {{ .Values.api.deployment.apiContainer.containerPort }}
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: JWT_SECRET_KEY
        - name: MONGO_DB_DOMAIN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: MONGO_DB_DOMAIN
        - name: MONGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: MONGO_DB_PORT
        - name: MONGO_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: MONGO_DATABASE_NAME
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: MONGO_DB_USER
        - name: MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: MONGO_DB_PASS
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.api.deployment.secretsName }}
              key: CORS_ORIGIN