apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.api.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  type: ClusterIP